# Generated by Django 4.1.3 on 2022-12-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='lastname',
        ),
    ]
