# Generated by Django 4.1.3 on 2022-12-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_remove_candidate_fullname_remove_voter_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
